# common
spring:
  profiles: 
    active: local

---
# local
spring:
  profiles: local
  jpa:
    show-sql: true
server:
    port: 9000
logging:
  level:
    com.todolist: debug

---
# test
spring:
  profiles: test
logging:
  level:
    com.todolist: info

---
# prd
spring:
  profiles: prd
logging:
  level:
    com.todolist: info
